services:
  - type: web
    name: ansh-ebook-frontend
    env: static
    buildCommand: npm install --prefix frontend && npm run build --prefix frontend
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: ansh-ebook-server
    env: node
    buildCommand: npm install --prefix server
    startCommand: npm start --prefix server
    envVars:
      - key: NODE_ENV
        value: production
